server:
    port: 8081
    error:
        whitelabel:
            enabled: false
spring:
    application:
        name: escooter-service
    mvc:
        view:
            prefix: /templates/
            suffix: .html
    profiles:
        active: prod