server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false
spring:
  application:
    name: escooter-service
  profiles:
    active: prod
  mvc:
    view:
      prefix: /templates/
      suffix: .html